# Generated by Django 4.0.3 on 2022-04-05 16:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('trainingPlan', '0001_initial'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='coach',
            name='plans',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coach_plans', to='trainingPlan.plan'),
        ),
        migrations.AddField(
            model_name='coach',
            name='sport_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coach_category', to='trainingPlan.category'),
        ),
        migrations.AddField(
            model_name='client',
            name='client',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
