# Generated by Django 4.0.3 on 2022-04-26 09:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trainingPlan', '0002_remove_plan_category_category_plan'),
        ('accounts', '0003_alter_coach_plans'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coach',
            name='plans',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='coach_plans', to='trainingPlan.plan'),
        ),
    ]
