# Generated by Django 4.0.3 on 2022-04-05 16:21

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=200)),
                ('desc', models.TextField(null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('published', models.DateTimeField(default=django.utils.timezone.now)),
                ('pdf', models.FileField(upload_to='')),
                ('image', models.ImageField(blank=True, upload_to='products/%Y/%m/%d')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='published', max_length=10)),
                ('category', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='plan_category', to='trainingPlan.category')),
                ('coach', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plan_coach', to='accounts.coach')),
            ],
            options={
                'ordering': ('-published',),
                'index_together': {('id', 'slug')},
            },
        ),
    ]
