# Generated by Django 4.0.3 on 2022-04-26 09:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trainingPlan', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plan',
            name='category',
        ),
        migrations.AddField(
            model_name='category',
            name='plan',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='plan_category', to='trainingPlan.plan'),
        ),
    ]
