# Generated by Django 4.0.3 on 2022-04-26 10:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trainingPlan', '0002_remove_plan_category_category_plan'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='plan',
        ),
        migrations.AddField(
            model_name='plan',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='plan_category', to='trainingPlan.category'),
        ),
    ]
